#FLAG=-std=c++11 -L/usr/lib64/mysql -lmysqlclient -ljsoncpp

db_test:db_test.cc
	g++  db_test.cc -o  db_test -std=c++11 -L/usr/lib64/mysql -lmysqlclient -ljsoncpp


.PHONY:clean
clean:
	rm db_test  


	
